<?php
//include the database connection string
    include_once "includes/connectionString.php";
    //SQL query to insert user to database
    // recieve the user's inputs through the form
    if ($_SERVER["REQUEST_METHOD"] == "POST")
    {
        $username = test_input($_POST["username"]); // store the user's sanitised input in the username, password and emailAddr variables
        $password = test_input($_POST["password"]);
        $emailAddr = test_input($_POST["email"]);

        $hash = password_hash($password, PASSWORD_DEFAULT); // salt and hash the user's password and store it in the hash variable



    }

    function test_input($data) // test_input function
    {
        $data = trim($data); $data = stripslashes($data); $data = htmlspecialchars($data); return $data; // strip whitespace, slashes and change special characters to html special characters, then return the data
    }

    $stmt = $conn->prepare("SELECT username FROM userInfo WHERE username=?"); // prepare a statement to take in the username from the database where username = ?
    $stmt->bind_param("s", $username); // bind the username to those paramaters to use it in the statement
    $stmt->execute(); // execute the statement
    $checkUnique = $stmt->fetch(); // set the checkUnique variable to true or false based on the fetch 
    if ($checkUnique) // if true
    {
        header("Location: register.php?error=username_taken"); // the username is take and the user must register another
    }

    $stmt = $conn->prepare("INSERT INTO userInfo (username, userPassword, emailAddr) VALUES (?,?,?)"); // else perpare a statement to insert the user's input into the database
    $stmt->bind_param("sss",$username,$hash,$emailAddr); // bind the paramaters to complete the statement

   


    if ($stmt->execute()) // if the statement executes
    {


        $userId = $conn->insert_id; //  returns the ID generated by an INSERT or UPDATE query on a table with a column having the AUTO_INCREMENT attribute


        ob_start(); // begin a session
        session_start();
        $_SESSION['username'] = $username; // set the username and userId
        $_SESSION['userId'] = $userId;
        if (!isset($_SESSION['username'])&&!isset($_SESSION['userId'])) // check that the session is set, if not send the user to the homepage
        {
            header("Location: index.php");
        }
        else
        {
            header("Location: userProfile.php"); // else send the user to the user profile page
        }
       
        
    }
    else
    {
        header("Location: register.php?error=query_failed"); // if the statement doesnt execute return to the register page and show error that the query failed
    }
    
    $stmt->close(); //close connections
    $conn->close();
    //redirect user back to registration page if unsuccessful, else go to user profile
    //header("Location: http://www.example.com/");
    

?>